### ISSUE TITLE
Добавить инвариант контейнера. Проверка пред- и постусловий

### ISSUE THREAD

**Issue by Axiino** [Gentser/Keknaizer#19]

**Comment by Gentser** [comment]
# Список возможных пред- и постусловий
## TimeLine

### 1) Добавление нового TimeLine
**Предусловия**  
* Длина `vector<TimeLine>`: **n, n>=0**
* `vector<TimeLine>` отсортирован
* `vector<TimeLine>` не содержит элементов с таким же именем, как у добавляемого `TimeLine` 
(**ПРИМЕЧАНИЕ:** или нет такого же ID?)
* Время начала `TimeLine` не позже, чем время его окончания 

**Постусловия**  
* Длина `vector<TimeLine>`: **n+1, n>=0**
* `vector<TimeLine>` содержит добавляемый элемент `TimeLine` 
* `vector<TimeLine>` отсортирован
* `vector<TimeLine>` не содержит дублирующихся элементов

### 2) Удаление TimeLine
**Предусловия**  
* Длина `vector<TimeLine>`: **n, n>0**
* `vector<TimeLine>` отсортирован
* `vector<TimeLine>` содержит искомый элемент `TimeLine` 
(**ПРИМЕЧАНИЕ:** ищем `TimeLine` по имени, или по ID?)

**Постусловия**  
* Длина `vector<TimeLine>`: **n-1, n>0**
* `vector<TimeLine>` отсортирован
* `vector<TimeLine>` не содержит удаленный элемент

### 3) Изменение TimeLine
**Предусловия и постусловия**  
* Длина `vector<TimeLine>`: **n, n>0**
* `vector<TimeLine>` отсортирован
* `vector<TimeLine>` содержит искомый элемент `TimeLine`
(**ПРИМЕЧАНИЕ:** ищем `TimeLine` по имени, или по ID?)
* `vector<TimeLine>` не содержит дублирующихся элементов


## TimeLineItem
### 1) Добавление нового TimeLineItem
**Предусловия**  
* Длина `vector<TimeLineItem>`: **n, n>=0**
* `vector<TimeLineItem>` отсортирован
* `vector<TimeLineItem>` не содержит элементов с таким же именем, как у добавляемого `TimeLineItem`
* Время начала `TimeLineItem` не позже, чем время его окончания 

**Постусловия**  
* Длина `vector<TimeLineItem>`: **n+1, n>=0**
* `vector<TimeLineItem>` содержит добавляемый элемент `TimeLineItem`
* `vector<TimeLineItem>` отсортирован
* `vector<TimeLineItem>` не содержит дублирующихся элементов

### 2) Удаление TimeLineItem
**Предусловия**  
* Длина `vector<TimeLineItem>`: **n, n>0**
* `vector<TimeLineItem>` отсортирован
* `vector<TimeLineItem>` содержит искомый элемент `TimeLineItem`

**Постусловия**  
* Длина `vector<TimeLineItem>`: **n-1, n>0**
* `vector<TimeLineItem>` отсортирован
* `vector<TimeLineItem>` не содержит удаленный элемент

### 3) Изменение TimeLineItem
**Предусловия и постусловия**  
* Длина `vector<TimeLineItem>`: **n, n>0**
* `vector<TimeLineItem>` отсортирован
* `vector<TimeLineItem>` содержит искомый элемент `TimeLineItem`
* `vector<TimeLineItem>` не содержит дублирующихся элементов

## GanttChart
### Отображение GanttChart
**Предусловия**  
* Элемент `GanttChart` существует
* Длина `GanttChart::vector<TimeLine>`: **n, n>0**

**Comment by Gentser** [comment]
@Axiino(Макс), добавил список возможных пред- и постусловий. Посмотри, пожалуйста, может добавить или изменить что нужно.
